config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  post '/transfer_product', to: 'home#transfer', as: 'transfer_product'

  mount ShopifyApp::Engine, at: '/'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/shop.rb
# frozen_string_literal: true

class Shop < ActiveRecord::Base
  include ShopifyApp::ShopSessionStorageWithScopes

  def api_version
    ShopifyApp.configuration.api_version
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authenticated_controller.rb
# frozen_string_literal: true

class AuthenticatedController < ApplicationController
  include ShopifyApp::EnsureHasSession
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  include ShopifyApp::EnsureInstalled
  include ShopifyApp::ShopAccessScopesVerification

  def index
    if ShopifyAPI::Context.embedded? && (!params[:embedded].present? || params[:embedded] != "1")
      redirect_to(ShopifyAPI::Auth.embedded_app_url(params[:host]) + request.path, allow_other_host: true)
    else
      @shop_origin = current_shopify_domain
      @host = params[:host]

      # Get other stores and current store products
      @other_stores = Shop.where.not(shopify_domain: @shop_origin)
      @products = ShopifyAPI::Product.all(limit: 10) # Adjust the limit as needed
    end
  end

  def transfer
    product_ids = params[:product_ids]
    target_store = params[:target_store]
  
    if product_ids.is_a?(Array)
      TransferProductJob.perform_later(product_ids, target_store, current_shopify_domain)
    else
      # If only a single product_id is provided, still pass it as an array
      TransferProductJob.perform_later([product_ids], target_store, current_shopify_domain)
    end
  
    redirect_to root_path, notice: "Product transfer initiated."
  end  
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < AuthenticatedController
  def index
    @products = ShopifyAPI::Product.all(limit: 10)
    render(json: { products: @products })
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://unpkg.com/@shopify/polaris@4.25.0/styles.min.css" />
    <title>Store Transfer</title>
  </head>
  <body>
    <h2>Select Store to Transfer</h2>
    <%= form_with url: transfer_product_path, method: :post, local: true do |f| %>
      <label for="storeSelect">Choose Target Store:</label>
      <select id="storeSelect" name="target_store">
        <% @other_stores.each do |store| %>
          <option value="<%= store.shopify_domain %>"><%= store.shopify_domain %></option>
        <% end %>
      </select>
      <h2>Products in Current Store</h2>
      <ul>
        <% @products.each do |product| %>
          <li>
            <input type="checkbox" id="product-<%= product.id %>" name="product_ids[]" value="<%= product.id %>">
            <label for="product-<%= product.id %>"><%= product.title %></label>
          </li>
        <% end %>
      </ul>
      <%= f.submit "Transfer Selected Products" %>
    <% end %>
    <script src="https://unpkg.com/@shopify/app-bridge@latest/umd/index.js"></script>
    <script>
      document.addEventListener("DOMContentLoaded", async () => {
        const apiKey = "<%= ENV['SHOPIFY_API_KEY'] %>";
        const shopOrigin = "<%= @shop_origin %>";

        var createApp = window["app-bridge"].default;
        var actions = window["app-bridge"].actions;
        var SessionToken = actions.SessionToken;

        var app = createApp({
          apiKey: apiKey,
          shopOrigin: shopOrigin,
          forceRedirect: true
        });

        // Request and save a session token for future requests
        app.dispatch(SessionToken.request());
        
        window.sessionToken = await new Promise((resolve) => {
          app.subscribe(SessionToken.Action.RESPOND, (data) => {
            resolve(data.sessionToken || "");
          });
        });
      });
    </script>
  </body>
</html>

app/views/layouts/_flash_messages.html.erb
<% content_for :javascript do %>
  <%= content_tag(:div, nil, id: 'shopify-app-flash', data: { flash: { notice: flash[:notice], error: flash[:error] } }) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShopifyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/embedded_app.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <% application_name = ShopifyApp.configuration.application_name %>
    <title><%= application_name %></title>
    <%= stylesheet_link_tag 'application' %>
    <% if ShopifyApp.use_webpacker? %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% elsif ShopifyApp.use_importmap? %>
      <%= javascript_importmap_tags %>
    <% else %>
      <%= javascript_include_tag 'application', "data-turbolinks-track" => true %>
    <% end %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="app-wrapper">
      <div class="app-content">
        <main role="main">
          <%= yield %>
        </main>
      </div>
    </div>

    <%= render 'layouts/flash_messages' %>

    <script src="https://unpkg.com/@shopify/app-bridge@2"></script>

    <%= content_tag(:div, nil, id: 'shopify-app-init', data: {
      api_key: ShopifyApp.configuration.api_key,
      shop_origin: @shop_origin || (@current_shopify_session.shop if @current_shopify_session),
      host: @host,
      debug: Rails.env.development?
    } ) %>

    <% if content_for?(:javascript) %>
      <div id="ContentForJavascript" data-turbolinks-temporary>
        <%= yield :javascript %>
      </div>
    <% end %>
  </body>
</html>